name: Test

on:
  push:
    branches: [main, master, release]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Pytest

    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Run tests
        run: make test
